# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-25 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infragramdocument',
            name='latitude',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infragramdocument',
            name='longitude',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=20),
            preserve_default=False,
        ),
    ]
