# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-25 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0002_auto_20160325_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='infragramdocument',
            name='ndvi_score',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=20),
            preserve_default=False,
        ),
    ]
